### ISSUE TITLE
ES6 function declaration shorthands are not supported

### ISSUE THREAD

**Issue by khusamov** [jurisv/nodejs.extdirect#35]
If you declare a set of API functions sootstvetsvii with ES6, ie without the keyword FUNCTION, the library fails parsing function arguments.

Error text:

```
\node_modules\extdirect\lib\api.js:194
            var r = argDecl[1].split(FN_ARG_SPLIT);
                           ^
TypeError: Cannot read property '1' of null
    at API.__dirname.API.config.reflection (\node_modules\extdirect\lib\api.js:194:28)
    at \node_modules\extdirect\lib\api.js:85:37
    at iterate (\node_modules\extdirect\lib\api.js:222:35)
    at \node_modules\extdirect\lib\api.js:241:25
    at FSReqWrap.oncomplete (fs.js:117:15)
```

Example API ad

``` javascript
module.exports = {

    create(params, callback) {

    },

    read(params, callback) {
        let data = [];

        for (let i = 0; i < 10; i++) {
            data.push({
                id: i + 1,
                title: `Запись номер ${i + 1}`
            });
        }

        callback(null, {
            total: data.length,
            data: data
        });
    },

    update(params, callback) {

    },

    destroy(params, callback) {

    }

};
```

On line 117 regular expression should be corrected:

```
var FN_ARGS = /^function\s*[^\(]*\(\s*([^\)]*)\)/m,
```

**Comment by jurisv** [comment]
Defining methods in ES6 way using shorthand syntax is not supported, but I will entertain this idea as it's supported by node.js and seems that fix is rather simple.
